//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tensho.GatewayServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GatewayServiceReference.IGateway")]
    public interface IGateway {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGateway/Push", ReplyAction="http://tempuri.org/IGateway/PushResponse")]
        string Push(string username, string password, string payload, int encryptionLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGateway/Push", ReplyAction="http://tempuri.org/IGateway/PushResponse")]
        System.Threading.Tasks.Task<string> PushAsync(string username, string password, string payload, int encryptionLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGateway/Pull", ReplyAction="http://tempuri.org/IGateway/PullResponse")]
        string Pull(string username, string password, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGateway/Pull", ReplyAction="http://tempuri.org/IGateway/PullResponse")]
        System.Threading.Tasks.Task<string> PullAsync(string username, string password, string guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGatewayChannel : GatewayServiceReference.IGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatewayClient : System.ServiceModel.ClientBase<GatewayServiceReference.IGateway>, GatewayServiceReference.IGateway {
        
        public GatewayClient() {
        }
        
        public GatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Push(string username, string password, string payload, int encryptionLevel) {
            return base.Channel.Push(username, password, payload, encryptionLevel);
        }
        
        public System.Threading.Tasks.Task<string> PushAsync(string username, string password, string payload, int encryptionLevel) {
            return base.Channel.PushAsync(username, password, payload, encryptionLevel);
        }
        
        public string Pull(string username, string password, string guid) {
            return base.Channel.Pull(username, password, guid);
        }
        
        public System.Threading.Tasks.Task<string> PullAsync(string username, string password, string guid) {
            return base.Channel.PullAsync(username, password, guid);
        }
    }
}
